#################### Layout ##########################

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

#################### Style ###########################

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# Style/FrozenStringLiteralComment:
#   EnforcedStyle: never

Style/EmptyMethod:
  EnforcedStyle: expanded

#################### Metrics #########################

Metrics/LineLength:
  Max: 120
