#!/bin/bash

count=$1
numbers=()

if [ -z $count ]
then
  echo 'pls enter number'
  exit
else
  while read line ; do
    arr=$(echo $line | sed -e 's/[^0-9 ]//g')

    numbers+="${arr[@]}"
  done
fi

result=($(echo ${numbers[*]}| tr " " "\n" | sort -r -n | tr "\n" " "))

echo ${result[@]::$count}
